summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-openbsd-7.6-amd64/releases/download/2025.07.24/pkg-config-0.29.2-openbsd-7.6-amd64.release.tar.xz 
bin-sha: 728ae6c19fa313a883d5a7574e7b007f57d45d58845c2eecf006a3a47fe02f82
